# private workspaces
SHOW WORKSPACES IN DATABASE "USER$CMEYER";
SHOW OBJECTS IN DATABASE "USER$<username>";

SHOW DATABASES LIKE 'dropped_user%';
SHOW WORKSPACES IN DATABASE DROPPED_USER$dropped_user_1754344912;

ALTER ACCOUNT SET USE_WORKSPACES_FOR_SQL = 'always';

# ----------------------------------------------------------
# shared workspaces

GRANT USAGE ON DATABASE db TO ROLE role;
GRANT CREATE WORKSPACE ON SCHEMA db.sch TO ROLE role;

CREATE WORKSPACE MY_DB.WORK.MY_WORKSPACE;
GRANT READ|WRITE ON WORKSPACE MY_DB.WORK.MY_WORKSPACE TO ROLE role;

ALTER WORKSPACE MY_DB.WORK.MY_WORKSPACE ADD LIVE VERSION FROM LAST;

LIST 'snow://workspace/MY_DB.WORK.MY_WORKSPACE/versions/head/';
ALTER WORKSPACE MY_DB.WORK.MY_WORKSPACE COMMIT;
ALTER WORKSPACE MY_DB.WORK.MY_WORKSPACE ABORT;

DROP WORKSPACE MY_DB.WORK.MY_WORKSPACE_V2;
