CREATE COMPUTE POOL tutorial_compute_pool
   MIN_NODES = 1 MAX_NODES = 1
   INSTANCE_FAMILY = CPU_X64_XS;

ALTER COMPUTE POOL <name> SUSPEND/RESUME/STOP ALL;

ALTER ACCOUNT SET DEFAULT_STREAMLIT_COMPUTE_POOL='my_pool';

SHOW COMPUTE POOL INSTANCE FAMILIES;

SELECT SYSTEM$GET_INSTANCE_FAMILY_PLACEMENT_GROUPS('GPU_NV_L');
